a-h/templ

cmd/templ/main.go

fix: ensure that both binary (goreleaser) and source (go install) builds get version numbers

---

cmd/templ/generatecmd/main.go

After some profiling of the generate command I had some interesting results.
I created a 10MB templ file which is the largest allowed then profiled the generation of it.
Ignoring any small effects profiling had on the speed it took around 2 minutes 50 seconds consistently.
Peaking at around 20MB allocated memory.
According to pprof the majority of this was time spent in `syscall`.
Using a file as an io.Reader was calling syscall a lot, which is slow.
So I tried writing to a buffer then writing the buffer and reduced this drastically.
It took about 8 seconds with a similar memory peak.

Write files to buffer rather than directly to files

---

parser/calltemplateparser.go
parser/calltemplateparser_test.go
parser/cssparser.go
parser/cssparser_test.go
parser/doctypeparser.go
parser/elementparser.go
parser/elementparser_test.go
parser/forexpressionparser.go
parser/forexpressionparser_test.go
parser/ifexpressionparser.go
parser/ifexpressionparser_test.go
parser/importparser.go
parser/importparser_test.go
parser/packageparser.go
parser/packageparser_test.go
parser/parser.go
parser/scripttemplateparser.go
parser/scripttemplateparser_test.go
parser/stringexpressionparser.go
parser/stringexpressionparser_test.go
parser/switchexpressionparser.go
parser/switchexpressionparser_test.go
parser/templateparser.go
parser/templateparser_test.go
parser/textparser.go

The current behaviour enforces spaces, so that expressions like `{%endtempl %}`, `{% endtempl%}` and `{%endtempl%}` are not valid. This can be annoying since if you only miss a space, the template won't compile.
This change updates the template handling to ignore missed spaces, and `templ fmt` reformats them to include the spaces, i.e. goes from `{%endtempl%}` to `{% endtempl %}`.

feat: stop enforcing spaces after '{%' and before '%}' (#35)

---

cmd/templ/fmtcmd/main.go

I can't format individual files. I want to plug `templ fmt` into https://github.com/mhartington/formatter.nvim
When `gofmt` isn't called with a path it reads from stdin.
When `fmt` is called with no parameters it reads from stdin, allowing you to do stuff like: `cat template.templ | templ fmt` which will print out the formatted template.
This breaks what fmt does currently, requring you to provide a directory for usual formatting, e.g. `templ fmt .`

feat(fmt): allow formatting from stdin

---

runtime.go
runtime_test.go

When including a hyphen in a regex it must come first: [-A-Z]

fix: regex syntax incorrect causing hyphenated classes to be sanitized.

---

generator/generator.go

Very niche issue that only manifests if you're doing some funky stuff with templ.
Template:
The raw function captures the rendered children and escapes (for code snippets).
```
@shared.Raw() {
<div>Joe</div>
}
```
Previous behaviour:
Notice that the closured template is writing to `templBuffer`, rather than `w`.
In most normal cases this is fine as the writer is the same, however in my case I have a custom component which handles the rendereing.
```go
// TemplElement
var_20 := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
// Element (standard)
_, err = templBuffer.WriteString("<div>")
....
return err
})
err = shared.Raw().Render(templ.WithChildren(ctx, var_20), templBuffer)
```
New behaviour:
Now it converts `w` to a `templBuffer`. `w` cannot be assumed to be a …

Block element fix

---

parser/v2/cssparser.go
parser/v2/cssparser_test.go
safehtml/style.go
safehtml/style_test.go

https://www.w3.org/TR/css-syntax-3/#ident-token-diagram

feat: allow preceeding dash in css ident token

---

cmd/templ/generatecmd/main.go
generator/generator.go

Hi,
first, thank you for templ, it's a cool project which I'm using more and more.
One thing I would like is to have the generated code properly formatted with gofmt. In my projects I always have a CI check that runs `gofmt -d .` to verify all my Go code is properly formatted but as of right now the code produced by templ is not properly formatted.
It's small stuff, for example taking the templates under `generator` and running `gofmt -d .`, we can see:
* incorrect indentation
```diff
-// Text
-var_4 := `
+               // Text
+               var_4 := `
$("div").marquee();
function test() {
window.open("https://example.com")
}
`
-_, err = templBuffer.WriteString(var_4)
-if err != nil {
-       return err
-}
+               _, err = templBuffer.WriteString(var_4)
+               if err …
```

feat: format generated code with gofmt

---

cmd/templ/fmtcmd/main.go

Currently `templ fmt /my/directory` is broken, it always formats the current directory.

fmtcmd: actually use the dir parameter

---

parser/v2/elementparser.go
parser/v2/elementparser_test.go

fix: bool constants can be followed by >

---

docs/docs/09-commands-and-tools/02-ide-support.md

Hi,
I've been working on a tree-sitter parser lately for Templ (see [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ)), which works quite well right now. Here are some screenshots
One area where it's quite good compared to templ.vim is highlighting Go code because I was able to reuse the Go tree-sitter [parser](https://github.com/tree-sitter/tree-sitter-go) for some things. 
Some other things don't work well yet (conditional attributes for example).
With this PR I'm proposing adding a link to [tree-sitter-templ](https://github.com/vrischmann/tree-sitter-templ) in the documentation page "IDE support", I believe it could be useful to others.

docs: link to tree-sitter-templ for Neovim

---

generator/generator.go
generator/test-element-attributes/expected.html
generator/test-element-attributes/template.templ
generator/test-element-attributes/template_templ.go
parser/v2/elementparser_test.go
parser/v2/types.go

fix: replace new lines in constant attributes with escaped new lines

---

cmd/templ/lspcmd/proxy/snippets.go

migrate `a` snippet from the old syntax

fix: migrate anchor tag snippet to 2.0 syntax

---

cmd/templ/generatecmd/main.go

This caught me by surprise when using `air` to auto-rebuild.
The `file.templ` was invalid and `templ generate` does not fail, it just prints the error. It caused the logical AND to succeed and rebuild while I kept working on the project and wondering why I'm not seeing my changes.
```toml
cmd = "templ generate && go build -o ./tmp/main ."
```
With this changes, it fails and the server dies, which is what I was expecting. 
Maybe it is just me, let me know what you think.
Cheers

Return error when generation fails

---

README.md

I think it would be useful to have a godoc badge in the README for easy access to the package documentation. If approved, please move it to where ever you like. I just put it towards the top like most README's, although it could make sense to put it under the documentation part.
Badge created via https://pkg.go.dev/badge/.

docs: Add godoc badge to README

---

docs/docs/08-hosting-and-deployment/02-hosting-using-docker.md
examples/counter-basic/Dockerfile

Since CGO is not required for this example, we can use the distroless static-debian11 image. This reduces the size of the image by 18 MB. Although this is just an example, I figured it would be nice show the usage of this static image in the docs.
```
counter-basic-static latest  635b8094b79a   10 seconds ago   10.6MB
counter-basic        latest  047d3cd36484   2 minutes ago    28.6MB
```

chore: Use static distroless image

---

generator/generator.go
generator/test-text-whitespace/render_test.go
generator/test-text-whitespace/template.templ
generator/test-text-whitespace/template_templ.go

I noticed while following the docs (specifically https://templ.guide/syntax-and-usage/expressions) that for the following template:
```
package main
templ greet(prefix string, p Person) {
<div>{ prefix } { p.Name }{ exclamation }</div>
}
```
The whitespace between `{prefix}` and `{p.Name}` is not preserved.  This is an attempt to fix that.

fix: maintain whitespace around templated values

---

docs/docs/03-syntax-and-usage/01-basic-syntax.md

Hi, I believe this example should be Go code, not the templ code.

docs: fix basic syntax example

---

docs/docs/02-quick-start/03-running-your-first-templ-application.md
docs/docs/03-syntax-and-usage/02-elements.md
docs/docs/03-syntax-and-usage/03-attributes.md
docs/docs/03-syntax-and-usage/07-loops.md
docs/docs/03-syntax-and-usage/09-css-style-management.md
docs/docs/04-core-concepts/01-components.md
docs/docs/04-core-concepts/02-template-generation.md
docs/docs/05-server-side-rendering/01-creating-an-http-server-with-templ.md
docs/docs/05-server-side-rendering/02-example-counter-application.md
docs/docs/05-server-side-rendering/03-htmx.md
docs/docs/06-static-rendering/01-generating-static-html-files-with-templ.md
docs/docs/06-static-rendering/02-blog-example.md
docs/docs/06-static-rendering/03-deploying-static-files.md
docs/docs/07-project-structure/01-project-structure.md
docs/docs/08-hosting-and-deployment/01-hosting-on-aws-lambda.md
docs/docs/10-security/index.md

Fixed many spelling mistakes and improved the clarity of some sentences. Feel free to request changes.
Please review carefully in case I messed up anything :smile:.

docs: minor clarity and spelling fixes

---

cmd/templ/generatecmd/main.go
cmd/templ/generatecmd/run/run.go

Fixes issue 4 in the #146 experience report.
Maybe add tests for the cli to prevent future issues.

fix: --cmd breaking with >1 argument, kill child processes correctly

---

docs/docs/02-quick-start/02-creating-a-simple-templ-component.md

The `Write()` method of `http.Request` writes the request content into a specified `io.Writer`, instead of writing specified bytes into itself.

doc: fix io.Writer examples

---

cmd/templ/generatecmd/main.go
cmd/templ/generatecmd/run/run.go

My recent PR (#181) had an issue where it would hang on the run on KillAll, as it would lock the mutex, then attempt to lock it again. This has been resolved by moving the KillAll to before the mutex is locked as part of Run.
This PR also renames KillAll to Stop for clarity.

fix: hang after m.Lock in KillAll (caused by #181)

---

README.md

Adds the Go Report card and centres all the cards in the README. 
You can see the layout [here](https://github.com/valxntine/templ/tree/update-readme-awesome-go)
Whilst aligning them all in the centre looks "nicer", its made me question if they would be better living under the Templ gif in the README rather than in the documentation section? I'll let someone else decide that and I can make the change if needs be.
Also if you don't care about the cards being in the centre, I can change that back. 
I don't think this specifically closes #196 but gets us a step closer as I can open a PR in awesome-go once this is all merged.

chore: update readme in preparation for awesome-go application

---

parser/v2/types.go
parser/v2/types_test.go

This PR solves the problem as written in the Issue #208 that `go templ` formats Go code which can be written alongside the `templ` keyword.
I'm still new to the go ecosystem but saw what was done in PR #102 with the `go/format` package. 
I think my little modification to format the code with this package when generating the clean string version is good.
Of course I'm open to any improvement.

feat: make templ fmt, format writen go code in templates

---

docs/docs/09-commands-and-tools/02-ide-support.md

Adds section to documentation on how to format `*.templ` files on save in neovim.

docs: add section for format on save in neovim

---

docs/docs/09-commands-and-tools/02-ide-support.md

fixes wrong order in the tailwindcss config introduced in my last PR

docs: fix typo/wrong order in neovim tailwindcss section

---

docs/docs/09-commands-and-tools/02-ide-support.md

Upcoming version will have `.templ` support: https://github.com/helix-editor/helix/pull/8540
Also added shell completion while I'm at it: https://github.com/rsteube/carapace-bin/pull/1910

doc: command-and-tools - added helix

---

cmd/templ/lspcmd/proxy/snippets.go

hey, found that there are some html tags that would be nice to have around, i know that there is a "default empty" tag that can be used but i thought having more makes it nicer to get going.
hopefully you find this helpful or can give some feedback.
im only starting to work with templ and im amazed by the tooling around it and its LSP, im super excited! 
cheers!

adds more standart html tags in snippets

---

cmd/templ/generatecmd/proxy/proxy.go

When deciding whether to modify response and include the SSE listener script, match the Content-Type header based on prefix only so `text/html; charset=utf-8` is also applicable.
based on #146

match prefix of Content-Type header in proxy

---

cmd/templ/generatecmd/proxy/proxy.go

Proxy will retry on error for 10 times, so server has some time to come up after reloading/restarting.
Tested with `templ generate --watch --proxy="http://127.0.0.1:8089" --proxyport="8080" --cmd="go run ."`
Open to ideas whether the backoff should be user configurable.
based on #146

feat: proxy retries with exponential backoff

---

docs/docs/02-quick-start/01-installation.md
flake.lock
flake.nix

I've added some extra functionality to the flake to make it easier to install on NixOS, and to use within a flake project.
I also updated the docs to help someone new to flakes to include this project in their own project.
There's also a new package `templ-docs`, so if you are hosting the docs on a NixOS system, you can host the static files using `services.nginx`.

Update flake and docs

---

flake.nix

Update the flake's go build vendor hash after ab819d4b1698f8f9463acb4699385372fcf89d0d.
I tested both packages build properly.

chore: update flake vendor hash

---

docs/docs/03-syntax-and-usage/09-template-composition.md

chore: remove reference to legacy template call expression

---

.github/workflows/ci.yml
README.md

Updated `xc fmt` tasks to include `templ fmt` and added a `ensure-fmt` step in CI to ensure all go and templ files are formatted.
Also:
- Update actions
- Add some missing code tags in readme

ci: Ensure fmt

---

parser/v2/types.go
parser/v2/types_test.go

Resolve #242 
Here I edit the way expressionAttribute are stringify by passing their expression to `go/format` only when those expression are multiline and contain period (sign of of a `Class expression` / slice)
Normally `go/format` can't format non valid Go Code so since technically we are in a virtual slice, I make the code append then after format remove a real slice.
It's maybe a little bit hacky but normally `Expression` should always have some valid go code so in the best I world, I shouldn't have to do that.
As usual, I am always open to suggestions.

Add support for formatting `ExpressionAttribute` with multiple line

---

docs/docs/03-syntax-and-usage/09-template-composition.md

`class="right"` should be `class="contents"` based on the components defined at the beginning of the *Components as parameters* section.

Correct class value in 09-template-composition.md

---

parser/v2/elementparser.go
parser/v2/elementparser_test.go

So this PR is exactly the same thing of my PR #212 except I make the maximum size twice as actual.
Why change again ? Is 32 not long enough ? Well yes and no for me...
In my project I need to create some custom element who represent an administration task form controller.
For this the name should be `<admin-create-reservation-controller>` since it's represent what the custom element do. 
***Except this example is 35 longs...***
So this is why I remade the same PR as #212.
But now I was wondering ? Why is Templ limit the maximum length of an element ? Web Component don't have any restriction on their name so why ?

Changing the maximum size of an element name to 128

---

docs/docs/04-core-concepts/04-view-models.md

Hi,
I think this should be `teamInviteComponent` instead of `teamInviteComponentModel` if I understand the code correctly. Sorry for the two PRs, just wanted to change the commit message.
Thanks!

docs: fix typo in "View model" page

---

docs/docs/07-project-structure/01-project-structure.md

Golang has moved the wiki from github to go.dev
See: https://github.com/golang/go/issues/61940

docs: fix wiki URL for interfaces

---

docs/docs/02-quick-start/02-creating-a-simple-templ-component.md

`go run *.go` doesn't work on Windows, whereas `go run .` is cross-platform and has the same effect in this case.
Fixes #331

docs: change `go run` command

---

cmd/templ/generatecmd/main.go
cmd/templ/main.go

Added default functionality to delete orphans on `templ generate`
& with the -keep-orphaned-files arg flag
(base2_templ.go isn't deleted)

Feature: default to delete orphaned files, with -keepOrphanedFiles argument flag to disable feature

---

docs/docs/04-core-concepts/01-components.md

I noticed that the last code block in [this docs page](https://templ.guide/core-concepts/components/) doesn't have syntax highlighting.

[docs] Enable templ syntax highlighting in 04-core-concepts/01-components

---

runtime.go
runtime_test.go

Proposed handler fixes and error handling improvements for #315
The general idea is to render component into a buffer before writing it to response, so that in the event of error, error handler can write its own response with correct status code and headers. The buffer is obtained with `GetBuffer()` and component should be able to use it directly as if it obtained buffer on its own.
Additionally, handler now sets headers to header map before writing response code, and does not write response code when calling error handler so that it can set its own headers and response code.

Response headers, status code, and error handling

---

cmd/templ/generatecmd/main.go
cmd/templ/main.go
cmd/templ/main_test.go
flake.nix
version.go

feat: show templ CLI and go.mod version mismatch warning

---

docs/docs/09-commands-and-tools/03-hot-reload.md

Added `wgo` as alternative to `air`.
It needs no config file, and has the MIT license.

Update 03-hot-reload.md: Added `wgo`

---

docs/docs/09-commands-and-tools/02-ide-support.md

Thanks for templ! I made an emacs major mode for it, reusing the tree-sitter parser that the neovim support uses.

docs: add emacs to editors with templ support

---

cmd/templ/lspcmd/proxy/server.go

Fixes #403
---
Fix is so trivial, I figured I'd just send it along so it's ready to go if needed.
If you'd like a little whimsy in the program-to-program comms, I was tempted to have the LSP call itself `templs`. If that appeals, happy to make that change :joy:

fix: report templ server info to LSP clients, not gopls info

---

cmd/templ/generatecmd/main.go

Currently `templ generate --watch` spams the version check on each loop.

fix: only run the version check once per command, to avoid spam.

---

docs/docs/06-static-rendering/02-blog-example.md

Fixes typo, using ! instead of @ to render body component

docs: Fixes typo on 02-blog-example.md

---

docs/docs/03-syntax-and-usage/03-attributes.md

resolves #422 
Documents how to use `templ.URL` for non-standard HTML elements/attributes ( e.g. HTMX's `hx-*` attributes )

docs: `templ.URL` sanitization for non-standard attributes

---

docs/docs/03-syntax-and-usage/03-attributes.md

the templ example has a hr, that is not shown as rendered in the output.

docs: Add missing hr render

---

parser/v2/templatefile.go
parser/v2/templatefile_test.go

fix: go expressions prior to templates with multiline args

---

docs/docs/03-syntax-and-usage/03-attributes.md

Hi, based on our discussion in #454, I added an example into docs on how to pass JSON object as HTML attribute value. I see that meanwhile same question already cropped up in #519. I stick to the more generic usecase so that it nudges the reader in the right way.

docs: Add JSON attribute example

---

cmd/templ/generatecmd/watcher/watch.go
cmd/templ/generatecmd/watcher/watch_test.go

feat: debounce generate watch events

---

examples/integration-gin/gintemplrenderer/renderer.go
examples/integration-gin/home.html
examples/integration-gin/main.go

Refactoring to better integrate with gin.HTML function (allow different http status code) and optionally add fallback html renderer to gin HTMLRender if no temp component is provided

docs: fix gin html status code overwrite and provide fallback renderer

---

parser/v2/goexpression/fuzz.sh
parser/v2/goexpression/parse.go
parser/v2/goexpression/parse_test.go
parser/v2/goexpression/testdata/fuzz/FuzzFuncs/46c9ed6c9d427bd2

Sometimes a panic could surface with the following incomplete code:
```
package main
templ 
```

fix: guard from index out of bounds error in function parsing

---

go.mod

Due to the inclusion of log/slog in https://github.com/a-h/templ/pull/470, this is the new minimum version.

Update minimum go version to 1.21

---

docs/docs/04-core-concepts/01-components.md

Based on #561 
This PR adds missing "os" import to the existing method component example and add a new example for inline struct initialization and component method calling.

chore(docs): add inline component example

---

docs/docs/04-core-concepts/03-testing.md

Integrated and adapted Adrian's [testing post](https://adrianhesketh.com/2021/10/17/testing-templ-html-rendering-with-goquery/) into the docs

docs: add more testing guidance

---

cmd/templ/processor/processor.go
cmd/templ/processor/processor_test.go

Resolves #599 
The `fmt` command now correctly handles the error without panicing
```
$ templ fmt "this path does not exist"
(✗)  [ error=lstat this path does not exist: no such file or directory ]
(✓) Format complete [ count=1 errors=1 duration=207.096µs ]
```

Check for non-nil error in FindTemplates

---

docs/docs/03-syntax-and-usage/03-attributes.md

I didn't go too wild with this one, so please let me know if you'd like anything added

docs: add documentation for functions in attribute expressions

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/main.go
cmd/templ/generatecmd/proxy/proxy.go
cmd/templ/generatecmd/testwatch/generate_test.go
cmd/templ/main.go
docs/docs/09-commands-and-tools/01-cli.md
docs/docs/09-commands-and-tools/03-hot-reload.md

I love this proxy option, it really makes web development easier! So first, thank you for creating `templ` and adding this awesome feature 🙇 
I wanted to use it with docker-compose, but because it's binding to `127.0.0.1` only, I could not use it from another container.
Here's a docker-compose.yaml example to show how it would be used:
```yaml
version: "3.8"
services:
web:
volumes:
- ./:/src/
ports:
- "3000:3000"
command: "go run /src/cmd/web/"
templ:
volumes:
- ./:/src/
ports:
- "7331:7331"
command: 'templ generate --watch --proxy="http://web:3000" --proxybind="0.0.0.0" --cmd="go run ./cmd/web/"'
```
Let me know what you think, if I can add any tests, etc 😊

feat: add `--proxybind`, giving the option to bind to something else than `127.0.0.1`

---

parser/v2/goexpression/parse_test.go
parser/v2/goexpression/scanner.go
parser/v2/templelementparser_test.go

fix: handle slice literals without named types

---

docs/docs/03-syntax-and-usage/03-attributes.md

There's a typo in https://templ.guide/syntax-and-usage/attributes .
This is a quick fix.

Fixing docs typo

---

runtime.go

Allow using `tel`, `ftp` and `ftps` as safe URL protocols

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/main.go
cmd/templ/generatecmd/proxy/proxy.go
cmd/templ/generatecmd/proxy/proxy_test.go
cmd/templ/main.go
docs/docs/09-commands-and-tools/03-hot-reload.md

[feat] implement notify proxy to reload browser

---

cmd/templ/generatecmd/proxy/proxy_test.go

@a-h Thanks for merging #661. I realised I left a redundant comment here.
I used testServer to terminate all connection after I notify proxy, but realised it doesn't work reliably. So now the test sse request listening goroutine will wait for expected result, or timeout to close the connection from the client side. Then the channels will receive and asset and close the test server in defer.

remove redudent comment

---

parser/v2/goexpression/parse_test.go
parser/v2/goexpression/scanner.go

fix: allow slice type definitions in templ expressions

---

parser/v2/raw.go
parser/v2/raw_test.go

Hello!
I have been using templ for a project where I am using non-standard HTML elements and I hit a parse error when I used a tag named `<scripts>`.
In the existing code, if the raw element name is successfully parsed, it immediately attempts to parse the attributes, without checking for whitespace or a closing `>`.
This means that something like `<scripts>` would be parsed as a `<script>` tag with a boolean attribute of `s` (the last character of the tag name). This would then give a confusing error about mismatched tags as the closing `</scripts>` tag was actually parsed correctly.
```
--- FAIL: TestRawElementParserIsNotGreedy (0.00s)
--- FAIL: TestRawElementParserIsNotGreedy/styles_tag (0.00s)
raw_test.go:115: unexpected error: <style>: expected end tag not present: line 0, col 8
--- …
```

Fix overly greedy parsing in raw elements parser

---

examples/integration-echo/main.go

While WriteHeader correctly infers the Content-Type as HTML in the example, the correct way to use ResponseWriter is to set the response headers first, then call WriteHeader.

fix: set headers before calling WriteHeader

---

examples/integration-echo/main.go

The previous implementation did not play nice with echo's error handler. The error handler does not override an already-set content-type, nor the response code (if already written to the underlying ResponseWriter), so error responses looked really weird. Eg you could get a code 200, content-type: text/html, with a json body.
This PR scraps that, and uses an implemtation really similar to what `templ.Handler` does, which is to allocate a byte buffer and render the component to that. This plays nice with the error handler and doesn't return any nonsense.

chore: update echo example

---

cmd/templ/generatecmd/proxy/proxy.go
cmd/templ/generatecmd/proxy/proxy_test.go

Fixes #742 
I have fallen back on the naive implementation if goquery fails.

feat: query for the body tag rather than using string replacements

---

parser/v2/formattestdata/multiline_string_literal_indentation_preserved.txt
parser/v2/types.go

Fixes #743 
The solution to this was a bit odd. I thought it would be more straight forward but no!
Essentially, I allow go fmt to format the code, then I indent everything by one, then format again. If go fmt removes the line then we are safe to auto-indent, but if the new indentation is preserved then we should leave it be.
Open to other solutions.

feat: preserve indentation of multiline go string literals

---

cmd/templ/generatecmd/proxy/proxy.go
cmd/templ/generatecmd/proxy/proxy_test.go

I realized that the relaod script tag was hard coded as a constant string. This was causing errors when using CSP with the newly added `WithNonce` function. 
I've made this PR so that the `modifyResponse` method parses the nonce from the request header (if present), and pass it along to `insertScriptTagIntoBody` to have it added to the script.

feat: add nonce to reload script

---

docs/docs/05-server-side-rendering/04-datastar.md

Typo in link to the Datastar examples in https://templ.guide/server-side-rendering/datastar

docs: Fix broken link

---

docs/docs/09-commands-and-tools/04-live-reload-with-other-tools.md

This PR fixes typo on page https://templ.guide/commands-and-tools/live-reload-with-other-tools/#reload-event: `build.bin` instead of `build.cmd` in "Note" block.

docs: fix typo in "Live reload with other tools"

---

docs/docs/03-syntax-and-usage/03-attributes.md

As example result `<p>` content is "Text".

fix(docs): add missing <p> content ("Text")

---

docs/docs/05-server-side-rendering/05-streaming.md

docs: fix typo in streaming documentation

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/eventhandler.go
cmd/templ/generatecmd/main.go
cmd/templ/generatecmd/test-eventhandler/eventhandler_test.go
cmd/templ/main.go
docs/docs/04-core-concepts/02-template-generation.md
docs/docs/09-commands-and-tools/01-cli.md

The `templ generate` command generates `.go` files from `.templ` files. When the `.go` file is newer than the `.templ` file it indicates that the `.templ` has not been updated since the `.go` file was generated. This means that the `.go` file is still valid and does not need to be generated again. *This ignores users manually editing the generated `.go` files, but there is usually not a good reason to do this.* 
This pull request contains a proposal to only generate the `.go` file if it is older than its source `.templ` file. This functionality was put behind a `--lazy` CLI flag to maintain backwards compatibility. 
~Aerek

feat: add support for lazy generation

---

parser/v2/elementparser.go
parser/v2/elementparser_test.go
parser/v2/forexpressionparser.go
parser/v2/forexpressionparser_test.go

refactor: allow for in flowing text if for statement not found

---

cmd/templ/lspcmd/lsp_test.go
cmd/templ/lspcmd/lspdiff/lspdiff.go
cmd/templ/lspcmd/proxy/server.go

Closes #893 
This took far too long to find but seems to resolve the issue for me

fix(lsp): update URI handling for non-templ files for references

---

cmd/templ/fmtcmd/main.go
cmd/templ/fmtcmd/main_test.go
cmd/templ/fmtcmd/testdata.txtar
cmd/templ/main.go
cmd/templ/processor/processor.go
docs/docs/09-commands-and-tools/01-cli.md

A common use with linters and formatters is checking in CI and failing if the formatter required any changed. This ensures that branches are never merged without the formatter being run.
This PR implements this functionality by tracking the number of files changed, and allowing the user to return an error exit code if `-fail` is provided, subsequently failing the CI job if formatting was not done before commit.
This PR also has the side benefit of providing additional user situational awareness as it now prints the number of changed files on every format run, even if the CI-fail flag is not used.
After merge, users can add the following to their CI to validate template formatting.
```
templ fmt -fail .
```
`fmt`'s help now looks like this:
```
./templ fmt --help
usage: templ fmt [<args> …
```

Add Formatting Fail Flag for CI Use

---

cmd/templ/lspcmd/lsp_test.go
cmd/templ/lspcmd/proxy/server.go
cmd/templ/testproject/testdata/remoteChild.templ
cmd/templ/testproject/testdata/remoteParent.templ

Fixes #911 
- Added logic to walk through workspace folders and initialize templ files.
- Logs warnings when source maps are not found in cache.
- Parses templates and sets source map cache contents.
- Handles errors during file reading, template parsing, and generation.
works on #911

feat(lsp): add workspace folder initialization

---

README.md

Without this fix, the generated [godoc](https://pkg.go.dev/github.com/a-h/templ) is polluted with links.

First link in README.md

---

parser/v2/goexpression/parse.go

Do not let whole contents of `src` escape to heap.
Fixes #916

parser: fix memory leak in goexpression.Func (fixes #916)

---

docs/docs/09-commands-and-tools/04-live-reload-with-other-tools.md

When setting up a new repo using these instructions, I was initially confused because the Tailwind css wasn't being updated when started with `make live`. Hitting Ctrl+C was also hanging due to the same wait.
Adding the `--yes` flag allowed the commands to proceed if installation was required. I didn't add any additional explanation, but happy to include some elaboration if preferred.

docs: Add --yes to npx commands

---

docs/docs/03-syntax-and-usage/10-template-composition.md
join.go
join_test.go

Heyoo, 
I have a PR for the proposal suggested in this [issue](https://github.com/a-h/templ/issues/788) I followed the example solution you given @a-h. I have updated the docs too to explain the new Join method with an example in the `Temple Composition` section. Let me know what you think. I will rename the commit message as part of any changes in the feedback

feat: templ.Join method renders multiple components into a single component

---

docs/docs/02-quick-start/01-installation.md

The example flake had at least two syntax errors which have been fixed. The example flake cannot be ran by itself so there might be more syntax errors.
I can replace it with a flake that actually works and can just be copied and pasted into a project if that is preferred.
The syntax errors were that the parenthesis were in the incorrect place.

fix: example flake syntax error

---

cmd/templ/main.go
docs/docs/04-core-concepts/02-template-generation.md
docs/docs/09-commands-and-tools/01-cli.md

The documentation of the `templ generate` command refers to the `-sourceMapVisualisations` argument. Using it generates the following error.
```bash
$ templ generate -sourceMapVisualisations .
flag provided but not defined: -sourceMapVisualisations
```
However, using the more conventionally named `-source-map-visualisations` argument successfully generates HTML files to visualize the templ code and its corresponding Go code, as shown below.
```bash
$ templ generate -source-map-visualisations
(✓) Complete [ updates=302 duration=520.239583ms ]
```
To resolve this, we can update the documentation to refer to the `-source-map-visualisations` argument instead.

docs: correct documentation for source-map-visualisations argument

---

docs/docs/09-commands-and-tools/02-ide-support.md

The links to the lspconfig documentations are broken, as the file was renamed from `server_configurations.md` to `configs.md`.

docs: correct links to lspconfig server configurations

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/eventhandler.go

I think this is removes the repeated error messages. Let me know if I've missed anything.
Example:
```
templ generate
(✗) Error [ error=failed to generate code for <file_here>: <file_here> parsing error: <p>: close tag not found: line 4, col 0 ]
(✗) Command failed: generation completed with 1 errors
```
Closes https://github.com/a-h/templ/issues/1011

fix: remove repeated error messages (#1011)

---

storybook/.gitignore
storybook/_package.json
storybook/storybook.go

feat: support latest version of Storybook

---

README.md
parser/v2/elementparser.go
parser/v2/elementparser_test.go
parser/v2/fuzz.sh

- **feat: support unquoted attribute values**
- **feat: add tests for unquoted attributes**
Closes #963

feat: support unquoted HTML attributes, closes #963

---

cmd/templ/imports/process.go
cmd/templ/imports/testdata/groups.txtar
cmd/templ/imports/testdata/groupsmanynewlines.txtar

This pr changes formatter to keep a new line between imports. For example, if you had such code:
```go
package main
import (
"fmt"
"strings"
"strconv"
)
var _, _ = fmt.Print("")
var _ = strings.Index("", "")
var _ = strconv.Quote("")
```
It would remove the empty line, but now it doesn't.
closes #939

feat: imports grouping

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/main_test.go

feat: delete watchmode files when shutdown is sent

---

docs/docs/03-syntax-and-usage/03-attributes.md
docs/docs/03-syntax-and-usage/12-script-templates.md
docs/docs/03-syntax-and-usage/17-using-react-with-templ.md
docs/docs/03-syntax-and-usage/18-render-once.md
docs/docs/10-security/01-injection-attacks.md
docs/docs/10-security/02-content-security-policy.md
examples/integration-react/components.templ
examples/integration-react/components_templ.go
generator/generator.go
generator/test-js-unsafe-usage/expected.html
generator/test-js-usage/expected.html
generator/test-js-usage/template.templ
generator/test-js-usage/template_templ.go
generator/test-once/expected.html
generator/test-once/template.templ
generator/test-once/template_templ.go
generator/test-only-scripts/expected.html
generator/test-raw-elements/expected.html
generator/test-raw-elements/template.templ
generator/test-raw-elements/template_templ.go
generator/test-script-inline/expected.html
generator/test-script-usage-nonce/expected.html
generator/test-script-usage/expected.html
js_test.go
scripttemplate.go
scripttemplate_test.go

[From the MDN docs about the script element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attribute_is_not_set_default_an_empty_string_or_a_javascript_mime_type):
> Attribute is not set (default), an empty string, or a JavaScript MIME type
> 
> Indicates that the script is a "classic script", containing JavaScript code. Authors are encouraged to omit the attribute if the script refers to JavaScript code rather than specify a MIME type. JavaScript MIME types are listed in the IANA media types specification.
I think it'd be good to reflect the best practices for `<script>` tag usage in templ docs.
Thank you for this library, and keep up the great work!

refactor: don't generate a `type` attribute for `<script>` elements, update associated docs

---

docs/docs/09-developer-tools/03-live-reload.md

Hello, I didn't realize I haven't been benefiting from live reload despite setting it up in my Makefile. After digging about today it turns out my use of https://github.com/go-swiss/compress Brotli middleware was causing issues, and that is not the case when using other gzip or middleware implementation. Without diving deeper, it seems weird that this compression middleware creates a problem, because it is using the same Brotli package as templ's under the hood for proxy.go. Probably a case of implementation where compressed handler got written to ResponseWriter and flushed, so there was nothing to inspect when templ got its chance.
Regardless, I think it'd be a good idea to clarify upfront that the Content-Type is important for the JS script insertion and hint at middleware …

docs: clarify when live reload might fail due to middleware implementation

---

docs/docs/02-quick-start/01-installation.md

Update templ installation docs to using the new tool directive in Go 1.24 with an info panel linking to the tool directive docs as described here https://github.com/a-h/templ/issues/1067

docs: go tool installation and info panel

---

docs/docs/09-developer-tools/02-ide-support.md

Update Vim documentation and add LSP plugin config example using `vim-lsp`.
It supports auto-formatting on save using LSP as well.
Also I didn't like how indentation worked in templ files, so I forked [joerdav/templ.vim](https://github.com/Joe-Davidson1802/templ.vim) and made it work more like Go files, but with some additions for opening/closing html tags. I added optional section about it, but can remove if you don't like that.

docs: improve vim documentation

---

cmd/templ/lspcmd/main.go
cmd/templ/lspcmd/proxy/server.go
cmd/templ/main.go

Allow disabling of language server preload through a command line flag to fix performance issues in large monorepos.
Closes #1117.

Conditionalize language server preload

---

.github/workflows/ci.yml

Potential fix for [https://github.com/a-h/templ/security/code-scanning/10](https://github.com/a-h/templ/security/code-scanning/10)
To fix the issue, we will add a `permissions` block at the workflow level to apply minimal permissions to all jobs. Since the workflow primarily involves CI tasks like building, testing, and linting, it likely only requires `contents: read`. If any job requires additional permissions, we can override the workflow-level permissions by adding a job-specific `permissions` block.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

chore: constrain CI/CD workflow permissions to read only

---

cmd/templ/main.go

To handle graceful shutdown requests, templ needs to handle `SIGTERM` signals from the operating system.
Templ is difficult to use in signal-based systems like `process-compose` because it does not gracefully shutdown, and thus, is unable to gracefully restart when externally signalled to do so.

feat: gracefully shutdown on sigterm in `-watch` mode 

---

cmd/templ/generatecmd/cmd.go
cmd/templ/generatecmd/eventhandler.go

When `-watch-pattern` is set and a non-go, non-text (`_templ.txt`) file changes that matches the pattern, processing the change is effectively a no-op because templ only restarts the `-cmd` when Go files change.
A use case for this change is when one uses `//go:embed` directives to embed non-Go assets in go binaries. E.g. when changes are made to `app.js` and `-cmd` is set to `go run main.go`, templ must restart the `-cmd` for changes to be seen. 
This change causes templ to re-run its "cmd" argument any time files matching its -watch-pattern change.

fix: include all watch patterns in consideration for cmd restart

---

docs/docs/03-syntax-and-usage/14-context.md

Hello! I have been using templ in a project and could not get the middleware context example to work.
I am quite sure that there is a typo in the documentation, but the same typo is present in issue [#253](https://github.com/a-h/templ/issues/253#issuecomment-1781844381)
It is either a typo, or I am just not understanding something really basic; sorry in advance!
**Before you begin**
templ version 0.3.906
**Describe the bug**
when passing `h` to http.ListenAndServer,  the resulting html is:
`<div class="--templ-css-class-unknown-type">Display</div>` 
when passing `withMiddleware` the resulting html is as expected: 
`<div class="red">Display</div>`
**To Reproduce**
1. create a main.templ file as:
```go
package main 
import (
"context"
"net/http"
)
... code in the docs
``` 
2. templ generate …

fix typo in http.ListenAndServer to use middleware

---

parser/v2/gocommentparser.go
parser/v2/gocommentparser_test.go
parser/v2/ifexpressionparser_test.go
parser/v2/templateparser_test.go
parser/v2/types.go

Hi there, I'm working on a Templ Linting tool for my project. In order to (a) display useful results to users and (b) enable linter config via comments (similar to eslint's `eslint-disable`), the tool needs to be able to understand the original source location of parsed nodes.
I came across a discussion thread on this topic and @joerdav seemed to agree that Templ's own parser should be able to support this: https://github.com/a-h/templ/discussions/586
So, here I am with what I hope to be the first of a handful of pull requests to add `Range`s to various parser nodes. I kept this one small to ensure that I'm following the right conventions, etc. Happy to receive feedback on the PR. I would like to make future PRs a bit longer so I'm not bombarding you with them, but if you prefer many …

feat: add Ranges to GoComment parser nodes

---

parser/v2/scriptparser.go
parser/v2/scriptparser_test.go
parser/v2/scriptparsertestdata/regexp_literal.txt

Fixes https://github.com/a-h/templ/issues/1243
But introduces an issue in code like this:
```
const result = call(1000 / 10, {{ data }}, 1000 / 10);
```
In the current PR, `/ 100, {{ data }}, 1000 /` would be collected as a regexp literal, and therefore, the `{{ data }}` go value wouldn't be interpolated.

fix: skip parsing of JavaScript regexp literals: `/test/`

---

parser/v2/elementparser.go
parser/v2/elementparser_test.go
parser/v2/forexpressionparser_test.go
parser/v2/ifexpressionparser_test.go
parser/v2/switchexpressionparser_test.go
parser/v2/templateparser_test.go
parser/v2/templelementparser_test.go
parser/v2/types.go

Hi again, back with another `Range` addition. This is the big one, haha.
Thank you for the reviews!
**Use case notes:** As mentioned previously, I'm working on a linting tool for Templ. `Element` seems like the most obvious in terms of being generally useful for such a tool, but I'll also throw out a few things in particular I'm thinking of.
- Disallow certain elements entirely: For example, `<iframe>`s. Or, in our case, we plan to have our own custom element replacements for certain tags to ensure compatibility and accessibility for clients and we want to ensure folks can't use the standard elements.
- Require certain attributes to be present: Obvious cases are `alt` for `<img>` and `href` for `<a>`. (I realize that dynamic attributes can make this challenging/impossible.)
- Prevent …

feat: add Range field to Element parser nodes

---

examples/suspense/main.templ

typo: suspense example 'WaitGround' -> 'WaitGroup'

---

parser/v2/calltemplateparser.go
parser/v2/calltemplateparser_test.go
parser/v2/types.go

Hi again, adding more `Range`s to parser nodes. `CallTemplateExpression` this time. About 2/3 of the way through!

feat: add `Range` to `CallTemplateExpression` nodes
