a-h/templ

- cmd/templ/lspcmd/snippets.go
- Added in css snippets
- Added "any html tag"
- Added missing % signs on some templ snippets
> Css snippets

- README.md
- generator/generator.go
- generator/test-doctype/render_test.go
- generator/test-doctype/template_templ.go
- generator/test-html/render_test.go
- generator/test-html/template.templ
- generator/test-html/template_templ.go
- parser/elementparser.go
- parser/elementparser_test.go
- parser/types.go
- runtime.go
> feat: add boolean attribute support

- cmd/templ/processor/processor.go
> fix: use dir

- cmd/templ/lspcmd/handler.go
> fix: enable DocumentFormattingProvider

- storybook/storybook.go
> feat: add option for preview-head.html

- parser/v2/templateparser.go
- parser/v2/templateparser_test.go
> fix: no matched nodes should be an error

- parser/v2/elementparser.go
- parser/v2/elementparser_test.go
> feat: parse single quote attributes

- docs/docs/03-syntax-and-usage/08-template-composition.md
Small copy pasta error in docs.
Really cool project!
> fix: docs: 03-syntax: 08-template: show correct html output

- generator/generator.go
- generator/test-css-expression/render_test.go
- generator/test-css-expression/template.templ
- generator/test-css-expression/template_templ.go
- parser/v2/types.go
> fix(#131): do not sanitize constant CSS properties within CSS templates

- generator/generator.go
- generator/test-script-usage/expected.html
- generator/test-script-usage/template.templ
- generator/test-script-usage/template_templ.go
> feat: support script templates for hx-on attributes

- safehtml/style.go
alphanumberics -> alphanumerics
> chore: fix typo in style.go

- docs/docs/09-commands-and-tools/02-ide-support.md
> docs: update neovim ide suppport

- docs/docs/09-commands-and-tools/02-ide-support.md
adds configs from #230 into docs
> docs: add IDE specific configs for tailwindcss

- docs/docs/02-quick-start/01-installation.md
- flake.nix
- fixes a typo in CGO_ENABLED
- fixes docs on how to use templ in a flake
PS: I'm having issues with the overlay instructions too, trying to figure out what's wrong... might be something on my config though :P
> fix: nix documentation

- docs/docs/02-quick-start/02-creating-a-simple-templ-component.md
> docs: add missing `go get` step

- examples/counter/services/count.go
Fixed the error message in the counter example
unkown -> unknown
> fix typo in ErrUnknownIncrementType

- flake.nix
- go.mod
- go.sum
- parser/v2/format_test.go
- parser/v2/testdata/templelement_multiline_block_containing_multiline_block.txt
- parser/v2/testdata/templelement_multiline_block_indentation.txt
- parser/v2/testdata/templelement_multiline_in_div.txt
- parser/v2/testdata/templelement_param_spacing.txt
- parser/v2/testdata/templelement_simple_block_indentation.txt
- parser/v2/testdata/templelement_simple_in_div.txt
- parser/v2/testdata/templelement_simple_no_change.txt
- parser/v2/types.go
> Format templ element expressions

- docs/docs/09-commands-and-tools/02-ide-support.md
Just a short snippet on how to activate Emmet for templ files
> docs: Add Emmet config for vscode

- examples/counter/main.go
Missed this when I updated the docs a few days ago
> Fixing example source to match docs

- docs/docs/09-commands-and-tools/02-ide-support.md
> docs: add a note for tailwind config file in the related section

- cmd/templ/fmtcmd/main.go
- cmd/templ/generatecmd/main.go
- cmd/templ/main.go
Also provide `-w` flag to allow limiting number of workers to 1 to provide idempotent output for multiple directories, and update to use new log handler for coloured log output and option to increase / decrease verbosity level.
Merges #462
> feat: fmt: allow formatting files and directories to stdout

- docs/docs/12-integrations/index.md
> docs: add list of project scaffolding tools

- cmd/templ/generatecmd/eventhandler.go
- cmd/templ/lspcmd/proxy/server.go
- parser/v2/diagnostics.go
- parser/v2/diagnostics_test.go
- parser/v2/elementparser.go
- parser/v2/forexpressionparser.go
- parser/v2/ifexpressionparser.go
- parser/v2/parser.go
- parser/v2/switchexpressionparser.go
- parser/v2/templatefile.go
- parser/v2/templateparser.go
- parser/v2/templelementparser.go
- parser/v2/types.go
> feat: refactor diagnostics and fix legacy call warning

- parser/v2/calltemplateparser_test.go
- parser/v2/goexpression/parse.go
- parser/v2/goexpression/parse_test.go
> fix: in all go inspect functions we want to stop at first match

- cmd/templ/generatecmd/cmd.go
- cmd/templ/generatecmd/eventhandler.go
- cmd/templ/generatecmd/main.go
- cmd/templ/main.go
> feat: add option to generate to stdout

- generator/test-spread-attributes/expected.html
- generator/test-spread-attributes/render_test.go
- runtime.go
I took a stab at adding support for this, but let me know if this isn't the behavior we'd expect from the API. 
Resolves #647
> Handle string and boolean pointers in attributes

- docs/docs/03-syntax-and-usage/03-attributes.md
> Fix documentation code block

- cmd/templ/generatecmd/proxy/script.js
> Make injected script able to be re-evaluated

- docs/docs/03-syntax-and-usage/09-template-composition.md
- docs/docs/main.go
This PR adds documentation to explicitly show how to import Templ components from other packages in the same project. The idea for this PR came up in this discussion: https://github.com/a-h/templ/discussions/554#discussioncomment-9178708.
> docs: Expand Syntax & Usage > Template Composition to show how to import components from different packages

- cmd/templ/generatecmd/proxy/proxy.go
I find that this error happens a lot. I'm on a intel machine rather than m1/m2 so things take a bit to start!
> feat: log url on proxy error, increase retries

- docs/docs/09-commands-and-tools/02-ide-support.md
> chore: document formatting with vim

- runtime.go
- runtime_test.go
> feat: support []CSSClass in class expression

- README.md
> docs: Update README.md for typo

- parser/v2/goexpression/parse_test.go
- parser/v2/goexpression/scanner.go
> fix: allow space after a period

- docs/docs/04-core-concepts/02-template-generation.md
define  small helper definition for making it easier for developers with using --watch flag
> Define tip for template generate watcher

- cmd/templ/generatecmd/symlink/symlink_test.go
- cmd/templ/generatecmd/watcher/watch.go
Fix #858.
Use suggestions from:
https://github.com/a-h/templ/issues/858#issuecomment-2245536447
https://github.com/a-h/templ/issues/858#issuecomment-2308354377
> fix: support symlinks, fixes #858

- docs/docs/09-commands-and-tools/03-live-reload.md
I couldn't find any reference to this flag. I see now there's another doc that has it, but that didn't come up when I was googling. Having it on this doc too will help I think.
> Add comment about open-browser flag

- docs/docs/05-server-side-rendering/04-datastar.md
#1022 - Fixed the example to be more in line with the most recent version of datastar. Also fixed a few typos and grammar issues.
> docs: update datastar example

- storybook/storybook.go
fix the wrong error return value
> fix: fix the wrong error return value

- parser/v2/scriptparser.go
- parser/v2/scriptparser_test.go
- parser/v2/scriptparsertestdata/non_js_script.txt
- parser/v2/types.go
Fixes https://github.com/a-h/templ/issues/1135
> fix: ignore non js scripting languages in script parser

- runtime.go
- runtime_test.go
> fix: add nonce attribute to style tag

- parser/v2/gocommentparser.go
- parser/v2/ifexpressionparser_test.go
- parser/v2/templateparser_test.go
Fixes https://github.com/a-h/templ/issues/1182
> fix: comments don't eat newlines

- cmd/templ/lspcmd/proxy/templdoclazyloader.go
- cmd/templ/lspcmd/proxy/templdoclazyloader_test.go
In the lazy loader, track the reference count of each package rather than the number of times each document has been opened. The latter stores redundant information since documents in a package are never opened individually. Rather, any document in a package is always opened in conjunction with all other documents in the same package. Managing reference counts at the package level simplifies the logic and avoids unnecessary redundancy.
> refactor: replace document open count with package reference count in lazy loader

- cmd/templ/generatecmd/run/run_unix.go
- cmd/templ/generatecmd/run/run_windows.go
> feat: pass stdin to watched commands

- cmd/templ/generatecmd/cmd.go
- cmd/templ/generatecmd/eventhandler.go
- cmd/templ/generatecmd/watcher/watch.go
- generator/generator.go
Fixes #1224, replaces #1190 and #1191.
> fix: stop rebuilding application if text-only changes have occurred in dev mode

- parser/v2/forexpressionparser.go
- parser/v2/forexpressionparser_test.go
- parser/v2/types.go
Hi! Back with another range addition.
> feat: add `Range`s to `ForExpression`s
